import os
from pathlib import Path
from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from django.core.management import call_command
from django.test import override_settings
from django.conf import settings
from playwright.sync_api import sync_playwright, expect
from accounts.models import User,Address
from catalog.models import Product
from orders.models import Order
from messaging.models import Notification,Message

@override_settings(CACHES={'default':{'BACKEND':'django.core.cache.backends.locmem.LocMemCache'}},EMAIL_BACKEND='django.core.mail.backends.locmem.EmailBackend')
class BrowserJourney(StaticLiveServerTestCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.artifacts=settings.BASE_DIR/'test-artifacts';cls.artifacts.mkdir(exist_ok=True)
    def tearDown(self):
        if hasattr(self,'browser'):
            for i,ctx in enumerate(self.browser.contexts):
                for j,pg in enumerate(ctx.pages):
                    try:
                        pg.screenshot(path=str(self.artifacts/f'last-{i}-{j}.png'),full_page=True)
                        if pg.locator('.empty').count(): print('Browser state:',pg.locator('#content').inner_text())
                    except Exception: pass
            self.browser.close()
        if hasattr(self,'pw'): self.pw.stop()
        super().tearDown()
    def test_full_customer_and_seller_journey(self):
        call_command('seed_demo',verbosity=0)
        User.objects.create_user(username='seller@example.test',email='seller@example.test',password='Seller-pass-726!',first_name='Seller',is_staff=True)
        self.pw=sync_playwright().start()
        self.browser=self.pw.chromium.launch(channel=os.getenv('BROWSER_CHANNEL','msedge'),headless=True)
        customer=self.browser.new_context(viewport={'width':1440,'height':1000})
        page=customer.new_page();page.set_default_timeout(10000);errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
        page.goto(self.live_server_url)
        expect(page.locator('.hero')).to_be_visible()
        page.screenshot(path=str(self.artifacts/'landing-desktop.png'),full_page=True)
        self.assertEqual(page.locator('img').evaluate_all('(imgs)=>imgs.filter(i=>!i.complete || !i.naturalWidth).length'),0)
        page.click('[data-auth="register"]')
        expect(page.locator('.language-options')).to_be_visible()
        self.assertEqual(page.locator('#auth-form').count(),0)
        page.click('[data-action="auth-language"][data-language="en"]')
        page.fill('[name="name"]','Demo Customer')
        page.fill('[name="email"]','customer@example.test')
        page.fill('[name="password"]','Customer-pass-726!')
        page.fill('[name="password_confirm"]','Customer-pass-726!')
        page.click('#auth-form button')
        page.wait_for_url('**/workspace/dashboard/')
        expect(page.locator('.metrics')).to_be_visible()
        page.goto(self.live_server_url+'/workspace/shop/')
        expect(page.locator('.product-card').first).to_be_visible()
        page.fill('#catalog-search','Blush')
        page.locator('#filter-form button').first.click()
        expect(page.locator('.product-card')).to_have_count(1)
        page.click('[data-action="reset-filters"]')
        expect(page.locator('.product-card')).to_have_count(5)
        page.click('.toolbar [data-action="finder"]')
        expect(page.locator('.guide-choices')).to_be_visible()
        for n in range(4):
            page.locator('.guide-choices button').last.click()
        expect(page.locator('.modal .product-card').first).to_be_visible()
        page.locator('.modal [data-action="quick-add"]').first.click()
        expect(page.locator('#toast')).to_contain_text('Added')
        page.click('[data-action="close"]')
        page.goto(self.live_server_url+'/workspace/cart/')
        expect(page.locator('.cart-row')).to_have_count(1)
        page.locator('[data-action="cart-quantity"]').last.click()
        expect(page.locator('[data-cart-variant]')).to_have_value('2')
        page.locator('.summary-card a').click()
        expect(page.locator('#checkout-form')).to_be_visible()
        page.fill('[name="phone"]','+998901234567')
        page.fill('[name="address"]','Local test delivery address')
        page.fill('[name="gift_message"]','A happy day <script>alert(1)</script>')
        page.select_option('#global-language','ru')
        expect(page.locator('[name="gift_message"]')).to_have_value('A happy day <script>alert(1)</script>')
        page.select_option('#global-language','en')
        expect(page.locator('[name="address"]')).to_have_value('Local test delivery address')
        page.click('#checkout-form button')
        expect(page.locator('.confirmation h1')).to_have_text('Your order has been received')
        self.assertEqual(page.locator('.contact-footer').count(),0)
        expect(page.locator('table tbody tr td').nth(1)).to_have_text('2')
        page.click('[data-action="contact-seller"]')
        page.fill('#conversation-form [name="body"]','Please use a pale ribbon.')
        page.click('#conversation-form button')
        expect(page.locator('.chat-history')).to_contain_text('Please use a pale ribbon.')
        # Independent seller session.
        seller=self.browser.new_context(viewport={'width':1440,'height':1000})
        admin=seller.new_page();admin.goto(self.live_server_url+'/auth/?role=admin')
        admin.click('[data-action="auth-language"][data-language="en"]')
        admin.fill('[name="email"]','seller@example.test');admin.fill('[name="password"]','Seller-pass-726!')
        admin.click('#auth-form button');admin.wait_for_url('**/manage/overview/')
        # Existing account locale is restored (default Uzbek), then changed through settings.
        admin.select_option('#global-language','en')
        admin.goto(self.live_server_url+'/manage/notifications/')
        expect(admin.locator('.notification')).to_contain_text('New order received')
        admin.locator('.notification a').click()
        admin.click('[data-action="order-status"][data-status="confirmed"]')
        expect(admin.locator('.badge')).to_have_text('Confirmed')
        admin.goto(self.live_server_url+'/manage/conversations/')
        admin.locator('.conversation-item').first.click()
        expect(admin.locator('.chat-history')).to_contain_text('Please use a pale ribbon.')
        admin.fill('#message-form [name="body"]','Of course. Your bouquet is confirmed.')
        admin.click('#message-form button')
        expect(admin.locator('.chat-history')).to_contain_text('Your bouquet is confirmed.')
        page.reload()
        page.locator('.conversation-item').first.click()
        expect(page.locator('.chat-history')).to_contain_text('Your bouquet is confirmed.')
        # Profile and address CRUD.
        page.goto(self.live_server_url+'/workspace/profile/')
        page.fill('#profile-form [name="first_name"]','Updated Customer')
        page.fill('#profile-form [name="phone"]','+998901234567')
        page.click('#profile-form button:not([type])')
        expect(page.locator('#profile-form [name="first_name"]')).to_have_value('Updated Customer')
        page.click('[data-action="new-address"]')
        page.fill('#address-form [name="label"]','Home')
        page.fill('#address-form [name="phone"]','+998901234567')
        page.fill('#address-form [name="address"]','Saved demo address')
        page.check('#address-form [name="is_default"]')
        page.click('#address-form button')
        expect(page.locator('.address-grid')).to_contain_text('Saved demo address')
        page.click('[data-action="edit-address"]')
        page.fill('#address-form [name="label"]','Studio')
        page.click('#address-form button')
        expect(page.locator('.address-grid')).to_contain_text('Studio')
        page.click('[data-action="delete-address"]');page.click('[data-action="confirm-address-delete"]')
        expect(page.locator('.address-grid .card')).to_have_count(0)
        page.goto(self.live_server_url+'/workspace/settings/')
        page.click('[data-action="set-theme"][data-theme="dark"]')
        page.reload();expect(page.locator('html')).to_have_attribute('data-theme','dark')
        page.click('[data-action="set-language"][data-language="ru"]')
        page.reload();expect(page.locator('html')).to_have_attribute('lang','ru')
        page.screenshot(path=str(self.artifacts/'settings-dark-russian.png'),full_page=True)
        # Customer cannot enter custom admin panel or invoke its backend.
        result=page.request.get(self.live_server_url+'/api/customers/')
        self.assertEqual(result.status,403)
        # Mobile layout, navigation drawer, images and reduced motion.
        mobile=self.browser.new_context(viewport={'width':390,'height':844},reduced_motion='reduce')
        mob=mobile.new_page();mob.goto(self.live_server_url)
        expect(mob.locator('.hero')).to_be_visible()
        self.assertLessEqual(mob.evaluate('document.documentElement.scrollWidth'),390)
        mob.screenshot(path=str(self.artifacts/'landing-mobile.png'),full_page=True)
        mob.click('[data-action="menu"]');expect(mob.locator('.sidebar')).to_have_class('sidebar open')
        mob.keyboard.press('Escape');expect(mob.locator('.sidebar')).to_have_class('sidebar')
        self.assertFalse(errors,errors)
        customer.close();seller.close();mobile.close()


    def test_admin_catalog_guide_and_customer_product_actions(self):
        call_command('seed_demo',verbosity=0)
        User.objects.create_user(username='owner@example.test',email='owner@example.test',password='Owner-pass-726!',first_name='Owner',is_staff=True,language='en')
        User.objects.create_user(username='buyer@example.test',email='buyer@example.test',password='Buyer-pass-726!',first_name='Buyer',language='en')
        self.pw=sync_playwright().start()
        self.browser=self.pw.chromium.launch(channel=os.getenv('BROWSER_CHANNEL','msedge'),headless=True)
        context=self.browser.new_context(viewport={'width':1440,'height':1000})
        page=context.new_page();page.set_default_timeout(10000)
        page.goto(self.live_server_url+'/auth/?role=admin')
        page.click('[data-action="auth-language"][data-language="en"]')
        page.fill('[name="email"]','owner@example.test');page.fill('[name="password"]','Owner-pass-726!')
        page.click('#auth-form button');page.wait_for_url('**/manage/overview/')
        page.goto(self.live_server_url+'/manage/categories/')
        page.click('[data-action="new-category"]')
        for key in ['name','description']:
            for lang in ['en','uz','ru']: page.fill(f'[name="{key}_{lang}"]','Test Collection '+lang)
        page.click('#catalog-form button')
        expect(page.locator('.address-grid')).to_contain_text('Test Collection en')
        page.goto(self.live_server_url+'/manage/products/')
        page.click('[data-action="new-product"]')
        for key in ['name','description','care']:
            for lang in ['en','uz','ru']: page.fill(f'[name="{key}_{lang}"]',('Test Bouquet ' if key=='name' else 'Fresh flowers ')+lang)
        page.click('#catalog-form button')
        expect(page.locator('#variant-edit-form')).to_be_visible()
        for lang in ['en','uz','ru']: page.fill(f'[name="name_{lang}"]','Classic '+lang)
        page.fill('[name="price"]','155000.50');page.fill('[name="stock"]','12')
        page.click('#variant-edit-form button')
        expect(page.locator('tbody')).to_contain_text('Test Bouquet en')
        row=page.locator('tbody tr').filter(has_text='Test Bouquet en')
        row.locator('[data-action="edit-variants"]').click()
        page.click('[data-action="variant-form"][data-id]')
        page.fill('[name="stock"]','8');page.click('#variant-edit-form button')
        expect(page.locator('tbody')).to_contain_text('Classic en: 8')
        page.screenshot(path=str(self.artifacts/'admin-catalog.png'),full_page=True)
        page.goto(self.live_server_url+'/manage/guide/')
        expect(page.locator('.json-editor')).to_be_visible()
        page.click('#guide-config-form button')
        expect(page.locator('#toast')).to_contain_text('Saved successfully')
        buyer_context=self.browser.new_context(viewport={'width':390,'height':844})
        buyer=buyer_context.new_page();buyer.goto(self.live_server_url+'/auth/')
        buyer.click('[data-action="auth-language"][data-language="en"]')
        buyer.fill('[name="email"]','buyer@example.test');buyer.fill('[name="password"]','Buyer-pass-726!')
        buyer.click('#auth-form button');buyer.wait_for_url('**/workspace/dashboard/')
        buyer.goto(self.live_server_url+'/workspace/shop/')
        expect(buyer.locator('.product-card').first).to_be_visible()
        buyer.locator('.product-picture').first.click()
        expect(buyer.locator('#product-form')).to_be_visible()
        buyer.fill('[name="quantity"]','2')
        buyer.click('#product-form button')
        expect(buyer.locator('#toast')).to_contain_text('Added to your cart')
        buyer.click('[data-action="favorite"]')
        expect(buyer.locator('#toast')).to_contain_text('Saved successfully')
        buyer.goto(self.live_server_url+'/workspace/shop/?favorites=true')
        expect(buyer.locator('.product-card')).to_have_count(1)
        self.assertLessEqual(buyer.evaluate('document.documentElement.scrollWidth'),390)
        page.goto(self.live_server_url+'/manage/products/')
        page.locator('tbody tr').filter(has_text='Test Bouquet en').locator('[data-action="archive-product"]').click()
        page.click('[data-action="confirm-archive"]')
        expect(page.locator('tbody tr').filter(has_text='Test Bouquet en')).to_contain_text('Archive')
        context.close();buyer_context.close()

